version: '3.8'

services:
  db:
    image: postgres:17.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    expose:
      - "8000"  # Это нужно для связи с Nginx
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
  nginx:
    image: nginx:1.24
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  # Новые тома 
  static_volume:
  media_volume:

